config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get 'email_invitations/new'

  get 'email_invitations/create'

  resources :email_invitations
  resources :meetings
  resources :friendships

  get "searches" => "searches#index", as: :searches
  get "searches/new" => "searches#new", as: :new_search
  get "searches/show" => "searches#show", as: :show_search

  

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}

  
  get "users" => "users#index", as: :users
  get "users/:id" => "users#show", as: :user

    resources :invites do
    resources :messages
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :meetings
  has_many :receivers, :through => :meetings
  has_many :inverse_meetings, :class_name => "Meeting", :foreign_key => "receiver_id"
  has_many :inverse_receivers, :through => :inverse_meetings, :source => :user
  

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  # to tell rails which foreign key to use
  has_many :invites, :foreign_key => :sender_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  has_attached_file :image, :styles => { :small => "64x64#", :med => "100x100#", :large =>"200x200>" }, :default_url =>"http://i.imgur.com/fj7eOAP.png"

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_many :sent_invitations, :class_name => 'Invitation', :foreign_key => 'sender_id'
  
  belongs_to :invitation
  # to exclude user and user's friends from the users index page
  scope :all_except, ->(user) { where.not(id: (user.friends + user.inverse_friends + [user]).map(&:id))}

    

def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.firstname = auth.info.first_name
    user.lastname = auth.info.last_name
    user.image = auth.info.image
    
    end
  end

def emailinvitation_token
  emailinvitation.token if emailinvitation
end 

def emailinvitation_token=(token)
  self.emailinvitation = EmailInvitation.find_by_token(token)

end 

# def self.all_except(user)
#   where.not(id: user)
# end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
      def index
      @users = User.all_except(current_user)
      end

	def new
	  @user = User.new(:emailinvitation_token => params[:emailinvitation_token])
	  @user.email = @user.emailinvitation.recipient_email if @user.emailinvitation
	end

  
  	
    def show
    	@user = User.find(params[:id])
      @total_friends = []
      @friends = current_user.friends.all
      @friends.each do |f|
        @total_friends << f
      end
      @inverse_friends = current_user.inverse_friends.all
      @inverse_friends.each do |fv|
        @total_friends << fv
      end 
      @total_meetings = []
    	@inverse_meetings = current_user.inverse_meetings.all
      @inverse_meetings.each do |inverse|
        @total_meetings <<inverse
      end 
    	@meetings = current_user.meetings.all
      @meetings.each do |a|
        @total_meetings << a
      end 

    	respond_to do |format|
            		format.html {
                	render
            	}
            	format.json {
                render json: @total_meetings
            	}
          end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
y
<div class="all-users">
	<div class="container">

		<div class="row users">

		<h1 class="our-users">our users </h1>

			
			<% @users.each do |u| %>
			<div class="user col-md-4">
			<td> <%= image_tag u.image, :class=> "profile-image"%></td><br><br>
			<td> <%= u.firstname%> <%= u.lastname%></td><br><br>
			


			<!-- <td><%#= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
		                    "data-sid" => current_user.id, "data-rip" => u.id %>
	      		</td><br> -->
	   
	    		
	      		<td><%= link_to "add to contact", friendships_path(:friend_id => u), :method => :post, class: "btn btn-default btn-lg" %></td><br><br>
	      		<!-- <td><%#= link_to "Add a Meetme", new_meeting_path(:params =>{:receiver_id => u})%></td><br> -->
	      	
			
			</div>
			<% end %>


		</div>
	</div>

app/views/users/show.html.erb
<div class="user-profile">
	<div class="container">
		<p id="notice"><%= notice %></p>
		<div class='row'>
		

		<div class="left-box col-md-6">
		<div class="row">
		<div class="meetme col-md-12">
			<h3 class="btn btn-lg"> You sent <%= current_user.meetings.count%> meetme@ to your friends</h3>
			
			<% current_user.meetings[0..1].each do |m|%>
				<div class="meet-at btn btn-md btn-default ">
				<h4 ><%= m.name %> 
				with <%=m.receiver.firstname.upcase%>
				
				</h4>
				

			
				<%= link_to "See detail", meeting_path(m), class: "btn btn-md btn-default no-border"%>
				<%#= link_to "Edit", edit_meeting_path(m), class: "btn btn-md btn-default no-border" %>
				<%= link_to "Remove", m, :method => :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-md btn-default no-border" %>
				</div> <!-- meet-at -->
			<%end%>

		</div> <!-- close meetme -->
		<div class="meetme col-md-12">
			<h3 class="btn btn-lg"> You have <%=current_user.inverse_meetings.count%> from your friends</h3>
			<% current_user.inverse_meetings[0..1].each do |inverse| %>

				<div class="meet-at btn btn-md btn-default">
				<h4><%= inverse.name%> with <%=inverse.user.firstname.upcase %></h4>
				<%= link_to "See detail", meeting_path(inverse), class: "btn btn-md btn-default no-border" %>
				</div> <!-- meet-at -->
			<% end %>
		</div><!-- meetme -->

		<div class="col-md-12">
				
			<%=link_to "new meetme@", new_meeting_path, class: "btn btn-md btn-default border" %>
		</div>
		

		<!-- <div class="contactlist col-md-12" >

		<%#= link_to "All Contacts", friendships_path(current_user), class: "btn btn-md btn-default border" %><br>
		<%#= link_to "Add New Contact", users_path, class: "btn btn-md btn-default border"%><br>
		</div>	<!- close contact list -->

		</div>  <!-- row -->
		</div> <!-- col-md-6   -->
	<div id="map-canvas" class="col-md-6"></div>
	
	
		
	</div> <!-- close row -->
	</div> <!-- close container-->

</div> <!-- close user-profile -->
	