config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get 'email_invitations/new'

  get 'email_invitations/create'

  resources :email_invitations
  resources :meetings
  resources :friendships

  get "searches" => "searches#index", as: :searches
  get "searches/new" => "searches#new", as: :new_search
  get "searches/show" => "searches#show", as: :show_search

  

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}

  
  get "users" => "users#index", as: :users
  get "users/:id" => "users#show", as: :user

    resources :invites do
    resources :messages
  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

	def index
		@total_friends = []
		@friends = current_user.friends.all
		@friends.each do |f|
			@total_friends << f
		end
		@inverse_friends = current_user.inverse_friends.all
		@inverse_friends.each do |fv|
			@total_friends << fv
		end 
		

	end 

	def show
		@friendship = Friendship.find(params[:id])
	end

	def new
		@friendship = current_user.friendships.new
	end 
	def create
		@friendship = current_user.friendships.build(:friend_id => params[:friend_id])
		if @friendship.save
		flash[:notice] = "Added friend."
		redirect_to current_user
		else
		flash[:error] = "Unable to add friend."
		redirect_to current_user
		end
	end

	def destroy
		@friendship = current_user.friendships.find(params[:id])
  		@friendship.destroy
  		flash[:notice] = "Removed friendship."
 		 redirect_to current_user
	end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<div class="friendlist">

<div class="container">

	<div class="row all-friends">


<h2 class="our-users"> Your have <%= @total_friends.count %> friends </h2>

<% for friendship in current_user.friendships %>

	<div class="user col-md-4">
	<td class="col-md-12"><%= image_tag friendship.friend.image(:med), :class=> "profile-image" %></td><br>
	<td class="col-md-12">Name: <%= friendship.friend.firstname %><%=friendship.friend.lastname%></td><br>
	<td class="col-md-12">Email: <%= friendship.friend.email %></td><br>
	<%= link_to "remove", friendship, :method => :delete, class: "btn no-border" %><br>
	<%= link_to "See detail", friendship_path(friendship), class: "btn no-border" %><br>

	</div>
<% end %>


	<div class="col-md-12">
<% for user in current_user.inverse_friends %>
	<div class="user col-md-4">
	<td class="col-md-12"><%= image_tag user.image(:med), :class=> "profile-image"  %></td><br>
	<td class="col-md-12">Name: <%= user.firstname %></td><br>
	<td class="col-md-12">Email: <%= user.email%></td><br>
	</div>
<% end %>
</div>
</div>

</div>
</div>

app/views/friendships/show.html.erb
<div class="a-friend">
	<div class="container">
		<div class="row userpage">




<div class="col-md-12 user-box">
<%= image_tag @friendship.friend.image(:small), class: "profile-image"%>
<h2> <%= @friendship.friend.firstname %> <%= @friendship.friend.lastname%></h2>
<h3> <%= @friendship.friend.email %></h3>

<%= link_to "Remove", @friendship, :method => :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-md btn-default border"%><br>

<%= link_to "send a meetme@ invite", new_meeting_path(@friendship.friend_id), class: "btn btn-md btn-default border"%><br>
</div>
	</div>
</div>
</div>