config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get 'email_invitations/new'

  get 'email_invitations/create'

  resources :email_invitations
  resources :meetings
  resources :friendships

  get "searches" => "searches#index", as: :searches
  get "searches/new" => "searches#new", as: :new_search
  get "searches/show" => "searches#show", as: :show_search

  

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}

  
  get "users" => "users#index", as: :users
  get "users/:id" => "users#show", as: :user

    resources :invites do
    resources :messages
  end

end

app/views/layouts/_nav.html.erb
<div class='container nav-head'>
	<div class="row">
	<%if current_user %>
 
		<div class="col-md-2 navbar navbar-default">
		<h5><%= link_to "Home", user_path(current_user.id)%></h5>
		</div> 
		<div class="col-md-2 navbar navbar-default">
		<h5><%= link_to "All Users", users_path%></h5>
		</div> 
		<div class="col-md-2 navbar navbar-default">
		<h5><%= link_to "Invite a Friend!", new_email_invitation_path %></h5>
		</div>
		<div class="col-md-2 navbar navbar-default"> 
		<h5><%= link_to "Sign Out", destroy_user_session_path, :method => 'delete' %></h5>
		</div> 

		<div class="col-md-2">
			<h5>Hello <%= current_user.firstname%></h5>
		</div>
	<% end %>
	</div> <!-- close row div -->
    </div> <!-- close container div -->


   

app/views/layouts/_nav1.html.erb
<% if current_user %>

<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand">meetme@</a>

  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav"> 
      <li><a><%= link_to "home", user_path(current_user.id), class: "bar-name" %></a></li>
      <li><a><%= link_to "users", users_path, class: "bar-name" %></a></li>
       <li><a><%= link_to "invite friends!", new_email_invitation_path, class: "bar-name"%></a></li>

         <li><a><%= link_to "Fun Events", searches_path, class: "bar-name"%></a></li>
         

      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown">more...<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a><%=link_to "my meetme@", meetings_path%></a></li>
          <li><a><%=link_to "my contacts", friendships_path%></a></li>
         
          <li><a><%= link_to "Sign Out", destroy_user_session_path, :method => 'delete' %></a></li>
          
        </ul>
      </li>
          <li><a><h4>Hello <strong><%=current_user.firstname%></strong></h4></a></li>
         <li><a><%= image_tag current_user.image.url(:med)%></a></li>
    </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Meet-Me@</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <script type="text/javascript"
      src="//maps.googleapis.com/maps/api/js">
    </script>
    <link href='//fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
</head>
<body class="background col-xs-12 col-md-8">
<div class="home-nav col-xs-4">
<%= render partial: "layouts/nav1"%>
</div>
<!-- <div class="background"> -->
<div class="welcome">

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

  <%= yield %>

</div><!-- close welcome -->

</body>
</html>